# These are supported funding model platforms

tidelift: "npm/setup-php"
community_bridge: setup-php
issuehunt: shivammathur
patreon: shivammathur
liberapay: shivammathur
custom: https://www.paypal.me/shivammathur
